services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: issueflow
      POSTGRES_PASSWORD: issueflow
      POSTGRES_DB: issueflow
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db